# Generated by Django 6.0.5 on 2026-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_PATIENT', 'Pending (Patient)'), ('EN_ATTENTE', 'En Attente (Assistant)'), ('APPROVED', 'Approved (Doctor)'), ('REJECTED', 'Rejected (Doctor)')], default='PENDING_PATIENT', max_length=20),
        ),
    ]
